GL\HomeBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: GL\HomeBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sujet:
            type: string
            length: 255
        corps:
            type: text
    manyToOne:
        auteur:
            targetEntity: User
            inversedBy: messagesEnvoye
        destinataire:
            targetEntity: User
            inversedBy: messagesRecu
    lifecycleCallbacks: {  }
