gl_home_homepage:
    path:     /
    defaults: { _controller: GLHomeBundle:Accueil:show }

gl_home_mailpage:
    path:   /mail
    defaults: { _controller: GLHomeBundle:Message:showMailBox }

gl_home_sendmail:
    path: /mail/sendmail
    defaults: { _controller: GLHomeBundle:Message:sendMail}

    