gl_home_homepage:
    path:     /
    defaults: { _controller: GLHomeBundle:Accueil:show }

gl_home_mailpage:
    path:   /mail
    defaults: { _controller: GLHomeBundle:Message:showMailBox }

gl_home_sendmail:
    path: /mail/sendmail
    defaults: { _controller: GLHomeBundle:Message:sendMail }

gl_home_showmail:
    path:   /mail/show/{id}
    defaults: { _controller: GLHomeBundle:Message:show }

gl_home_sendmailpage:
    path:   /mail/showsendmail
    defaults: { _controller: GLHomeBundle:Message:showSendMail }

gl_home_sendnotification:
    path:   /notification/send
    defaults: { _controller: GLHomeBundle:Notification:create }

gl_home_shownotifications:
    path:   /notification/show
    defaults: { _controller: GLHomeBundle:Notification:show }